name: project-check
on: push
jobs:
  checking:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2

      - name: Installing node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: make install

      - name: Linting code
        run: make lint

      - name: Building project
        env:
          REACT_APP_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: make build